import { db, Brand, Payment, BidHistoryItem, ActivityItem } from "./index";
import { hashToken } from "../security/tokens";
import { normalizeUrl } from "../url/normalize";

export const SEED_BRANDS = [
  {
    id: "brand_synthetix",
    name: "Synthetix AI",
    websiteUrl: "https://synthetix.ai",
    category: "AI",
    description: "Autonomous intelligence infrastructure for next-gen reasoning models.",
    tagline: "Autonomous Reasoning at Scale",
    logoUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80",
    totalBid: 10000,
    template: "typography" as const,
    token: "synthetix_super_secret_token_2026",
    daysAgo: 14,
  },
  {
    id: "brand_veloce",
    name: "Veloce Dev",
    websiteUrl: "https://veloce.dev",
    category: "Developer Tools",
    description: "Zero-latency build system and incremental compilation engine for TypeScript.",
    tagline: "Lightning Fast Rust Builds",
    logoUrl: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=200&auto=format&fit=crop&q=80",
    totalBid: 7500,
    template: "logo_dominant" as const,
    token: "veloce_super_secret_token_2026",
    daysAgo: 12,
  },
  {
    id: "brand_hyperflow",
    name: "HyperFlow",
    websiteUrl: "https://hyperflow.io",
    category: "SaaS",
    description: "Real-time collaborative canvas for engineering and product architecture.",
    tagline: "Visual Systems for Engineering",
    logoUrl: "https://images.unsplash.com/photo-1557683316-973673baf926?w=200&auto=format&fit=crop&q=80",
    totalBid: 5800,
    template: "editorial" as const,
    token: "hyperflow_super_secret_token_2026",
    daysAgo: 10,
  },
  {
    id: "brand_payzen",
    name: "PayZen",
    websiteUrl: "https://payzen.finance",
    category: "Fintech",
    description: "Modern global treasury management and cross-border settlement rails.",
    tagline: "Borderless Financial Rails",
    logoUrl: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=200&auto=format&fit=crop&q=80",
    totalBid: 4200,
    template: "minimal" as const,
    token: "payzen_token_2026",
    daysAgo: 9,
  },
  {
    id: "brand_kubecraft",
    name: "KubeCraft",
    websiteUrl: "https://kubecraft.cloud",
    category: "Developer Tools",
    description: "Effortless multi-cloud Kubernetes orchestration with automated autoscaling.",
    tagline: "Kubernetes Without the Tears",
    logoUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=200&auto=format&fit=crop&q=80",
    totalBid: 3500,
    template: "typography" as const,
    token: "kubecraft_token_2026",
    daysAgo: 8,
  },
  {
    id: "brand_omnitrack",
    name: "OmniTrack",
    websiteUrl: "https://omnitrack.so",
    category: "SaaS",
    description: "All-in-one product analytics and session replay built for privacy-first teams.",
    tagline: "Privacy-First Product Analytics",
    logoUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=200&auto=format&fit=crop&q=80",
    totalBid: 2800,
    template: "editorial" as const,
    token: "omnitrack_token_2026",
    daysAgo: 7,
  },
  {
    id: "brand_draftwave",
    name: "DraftWave",
    websiteUrl: "https://draftwave.studio",
    category: "Agency",
    description: "Brand identity and tactile digital experiences for bold category creators.",
    tagline: "Tactile Digital Brands",
    logoUrl: "https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=200&auto=format&fit=crop&q=80",
    totalBid: 2200,
    template: "logo_dominant" as const,
    token: "draftwave_token_2026",
    daysAgo: 6,
  },
  {
    id: "brand_zenithos",
    name: "Zenith OS",
    websiteUrl: "https://zenithos.co",
    category: "Consumer",
    description: "A focused, distraction-free spatial computing environment for deep work.",
    tagline: "Spatial Computing for Deep Work",
    logoUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=200&auto=format&fit=crop&q=80",
    totalBid: 1800,
    template: "minimal" as const,
    token: "zenithos_token_2026",
    daysAgo: 5,
  },
  {
    id: "brand_pulsegraph",
    name: "PulseGraph",
    websiteUrl: "https://pulsegraph.ai",
    category: "AI",
    description: "Graph neural networks for predictive biosensors and health metrics.",
    tagline: "Predictive Neural Health",
    logoUrl: "https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=200&auto=format&fit=crop&q=80",
    totalBid: 1500,
    template: "typography" as const,
    token: "pulsegraph_token_2026",
    daysAgo: 5,
  },
  {
    id: "brand_cartlogic",
    name: "CartLogic",
    websiteUrl: "https://cartlogic.shop",
    category: "E-commerce",
    description: "High-conversion headless checkout engine with 1-click international payments.",
    tagline: "Headless E-commerce Checkout",
    logoUrl: "https://images.unsplash.com/photo-1556742049-0a67e5572293?w=200&auto=format&fit=crop&q=80",
    totalBid: 1200,
    template: "editorial" as const,
    token: "cartlogic_token_2026",
    daysAgo: 4,
  },
  {
    id: "brand_skillforge",
    name: "SkillForge",
    websiteUrl: "https://skillforge.academy",
    category: "Education",
    description: "Interactive browser-based simulators for mastering backend systems.",
    tagline: "Master Real Backend Systems",
    logoUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=200&auto=format&fit=crop&q=80",
    totalBid: 1000,
    template: "typography" as const,
    token: "skillforge_token_2026",
    daysAgo: 4,
  },
  {
    id: "brand_byteforge",
    name: "ByteForge",
    websiteUrl: "https://byteforge.dev",
    category: "Developer Tools",
    description: "WebAssembly execution runtime for micro-services with instant cold starts.",
    tagline: "Instant WASM Microservices",
    logoUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=200&auto=format&fit=crop&q=80",
    totalBid: 850,
    template: "minimal" as const,
    token: "byteforge_token_2026",
    daysAgo: 3,
  },
  {
    id: "brand_aeromail",
    name: "AeroMail",
    websiteUrl: "https://aeromail.app",
    category: "SaaS",
    description: "Keyboard-driven email client designed for ultra high-volume founders.",
    tagline: "Inbox Zero in 60 Seconds",
    logoUrl: "https://images.unsplash.com/photo-1596524430615-b46475ddff6e?w=200&auto=format&fit=crop&q=80",
    totalBid: 750,
    template: "logo_dominant" as const,
    token: "aeromail_token_2026",
    daysAgo: 3,
  },
  {
    id: "brand_lumina",
    name: "Lumina AI",
    websiteUrl: "https://lumina.vision",
    category: "AI",
    description: "Generative video relighting and camera control for cinema VFX.",
    tagline: "Cinema-Grade AI Relighting",
    logoUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=200&auto=format&fit=crop&q=80",
    totalBid: 650,
    template: "editorial" as const,
    token: "lumina_token_2026",
    daysAgo: 2,
  },
  {
    id: "brand_finstack",
    name: "FinStack",
    websiteUrl: "https://finstack.xyz",
    category: "Fintech",
    description: "Programmable corporate credit cards and automated expense reconciliation.",
    tagline: "Programmable Spend Control",
    logoUrl: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=200&auto=format&fit=crop&q=80",
    totalBid: 550,
    template: "typography" as const,
    token: "finstack_token_2026",
    daysAgo: 2,
  },
  {
    id: "brand_nordic",
    name: "Nordic Design",
    websiteUrl: "https://nordicdesign.co",
    category: "Agency",
    description: "Minimalist Scandinavian digital product design and design systems.",
    tagline: "Pure Scandinavian UI/UX",
    logoUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=200&auto=format&fit=crop&q=80",
    totalBid: 480,
    template: "minimal" as const,
    token: "nordic_token_2026",
    daysAgo: 2,
  },
  {
    id: "brand_pixelcraft",
    name: "PixelCraft",
    websiteUrl: "https://pixelcraft.design",
    category: "Consumer",
    description: "Generative retro pixel art editor and animation suite for indie game devs.",
    tagline: "Retro Pixel Art Suite",
    logoUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=200&auto=format&fit=crop&q=80",
    totalBid: 420,
    template: "logo_dominant" as const,
    token: "pixelcraft_token_2026",
    daysAgo: 1,
  },
  {
    id: "brand_cloudnest",
    name: "CloudNest",
    websiteUrl: "https://cloudnest.io",
    category: "Developer Tools",
    description: "Instant ephemeral dev environments spawned in under 2 seconds.",
    tagline: "Ephemeral Dev Sandboxes",
    logoUrl: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=200&auto=format&fit=crop&q=80",
    totalBid: 360,
    template: "typography" as const,
    token: "cloudnest_token_2026",
    daysAgo: 1,
  },
  {
    id: "brand_nexuspay",
    name: "NexusPay",
    websiteUrl: "https://nexuspay.co",
    category: "Fintech",
    description: "Unified recurring billing and subscription optimization.",
    tagline: "Smarter Recurring Revenue",
    logoUrl: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=200&auto=format&fit=crop&q=80",
    totalBid: 300,
    template: "editorial" as const,
    token: "nexuspay_token_2026",
    daysAgo: 1,
  },
  {
    id: "brand_algotutor",
    name: "AlgoTutor",
    websiteUrl: "https://algotutor.io",
    category: "Education",
    description: "Visual step-by-step debugger for complex graph and dynamic programming algorithms.",
    tagline: "Visual Algorithm Mastery",
    logoUrl: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=200&auto=format&fit=crop&q=80",
    totalBid: 250,
    template: "minimal" as const,
    token: "algotutor_token_2026",
    daysAgo: 1,
  },
  {
    id: "brand_shopvibe",
    name: "ShopVibe",
    websiteUrl: "https://shopvibe.store",
    category: "E-commerce",
    description: "AI-curated shopping assistant embedded directly in social feeds.",
    tagline: "Social Commerce AI",
    logoUrl: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=200&auto=format&fit=crop&q=80",
    totalBid: 200,
    template: "typography" as const,
    token: "shopvibe_token_2026",
    daysAgo: 1,
  },
  {
    id: "brand_datapulse",
    name: "DataPulse",
    websiteUrl: "https://datapulse.net",
    category: "AI",
    description: "Automated anomaly detection for streaming time-series data.",
    tagline: "Stream Anomaly Detection",
    logoUrl: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=200&auto=format&fit=crop&q=80",
    totalBid: 160,
    template: "logo_dominant" as const,
    token: "datapulse_token_2026",
    daysAgo: 0,
  },
  {
    id: "brand_vectorstudio",
    name: "VectorStudio",
    websiteUrl: "https://vectorstudio.design",
    category: "Agency",
    description: "Custom 3D shaders and WebGL interactions for high-end digital agency portfolios.",
    tagline: "WebGL & 3D Shaders",
    logoUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=200&auto=format&fit=crop&q=80",
    totalBid: 120,
    template: "editorial" as const,
    token: "vectorstudio_token_2026",
    daysAgo: 0,
  },
  {
    id: "brand_codesprint",
    name: "CodeSprint",
    websiteUrl: "https://codesprint.dev",
    category: "Education",
    description: "Gamified multiplayer coding battles and live technical tournaments.",
    tagline: "Multiplayer Coding Battles",
    logoUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=200&auto=format&fit=crop&q=80",
    totalBid: 90,
    template: "minimal" as const,
    token: "codesprint_token_2026",
    daysAgo: 0,
  },
  {
    id: "brand_launchpad",
    name: "LaunchPad",
    websiteUrl: "https://launchpad.tools",
    category: "Other",
    description: "Boilerplate templates and marketing toolkit for indie hackers.",
    tagline: "Ship in 48 Hours",
    logoUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=200&auto=format&fit=crop&q=80",
    totalBid: 60,
    template: "typography" as const,
    token: "launchpad_token_2026",
    daysAgo: 0,
  },
  {
    id: "brand_syncpoint",
    name: "SyncPoint",
    websiteUrl: "https://syncpoint.io",
    category: "SaaS",
    description: "CRDT sync engine for offline-first React applications.",
    tagline: "Offline-First CRDT Sync",
    logoUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=200&auto=format&fit=crop&q=80",
    totalBid: 30,
    template: "typography" as const,
    token: "syncpoint_token_2026",
    daysAgo: 0,
  },
];

export async function seedDatabase() {
  console.log("🌱 Starting BrandBid database seeding (USD)...");

  const brands: Brand[] = [];
  const payments: Payment[] = [];
  const bidHistory: BidHistoryItem[] = [];
  const activity: ActivityItem[] = [];

  const now = Date.now();

  for (let i = 0; i < SEED_BRANDS.length; i++) {
    const item = SEED_BRANDS[i];
    const createdTimestamp = new Date(now - item.daysAgo * 86400000 + i * 3600000).toISOString();
    const tokenHash = hashToken(item.token);
    const canonical = normalizeUrl(item.websiteUrl);
    const slug = item.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

    const brand: Brand = {
      id: item.id,
      websiteUrl: item.websiteUrl,
      canonicalUrl: canonical,
      slug,
      name: item.name,
      category: item.category,
      logoUrl: item.logoUrl,
      description: item.description,
      tagline: item.tagline,
      totalBid: item.totalBid,
      status: "published",
      managementTokenHash: tokenHash,
      template: item.template,
      clickCount: Math.floor(Math.random() * 45) + 5,
      createdAt: createdTimestamp,
      updatedAt: createdTimestamp,
    };
    brands.push(brand);

    const paymentId = `pay_seed_${item.id.replace("brand_", "")}`;
    const orderId = `order_seed_${item.id.replace("brand_", "")}`;
    const payment: Payment = {
      id: paymentId,
      brandId: item.id,
      providerPaymentId: paymentId,
      providerOrderId: orderId,
      amount: item.totalBid,
      currency: "USD",
      status: "verified",
      createdAt: createdTimestamp,
      verifiedAt: createdTimestamp,
    };
    payments.push(payment);

    const historyItem: BidHistoryItem = {
      id: `hist_${paymentId}`,
      brandId: item.id,
      paymentId: paymentId,
      amountAdded: item.totalBid,
      previousTotal: 0,
      newTotal: item.totalBid,
      previousRank: null,
      newRank: i + 1,
      createdAt: createdTimestamp,
    };
    bidHistory.push(historyItem);

    const isNo1 = i === 0;
    const eventType = isNo1 ? "became_number_one" : "brand_entered";
    const activityItem: ActivityItem = {
      id: `act_${paymentId}`,
      brandId: item.id,
      eventType,
      metadata: {
        brandName: item.name,
        rank: i + 1,
        amount: item.totalBid,
        slug,
      },
      createdAt: createdTimestamp,
    };
    activity.push(activityItem);
  }

  // Add recent climbs
  activity.unshift(
    {
      id: "act_climb_1",
      brandId: "brand_veloce",
      eventType: "rank_climbed",
      metadata: {
        brandName: "Veloce Dev",
        previousRank: 5,
        newRank: 2,
        slug: "veloce-dev",
      },
      createdAt: new Date(now - 1000 * 60 * 15).toISOString(),
    },
    {
      id: "act_bid_1",
      brandId: "brand_synthetix",
      eventType: "bid_increased",
      metadata: {
        brandName: "Synthetix AI",
        amountAdded: 2500,
        newTotal: 10000,
        slug: "synthetix-ai",
      },
      createdAt: new Date(now - 1000 * 60 * 45).toISOString(),
    }
  );

  db.resetState({
    brands,
    payments,
    bidHistory,
    activity,
  });

  console.log(`✅ Successfully seeded ${brands.length} brands in USD with verified payments, bid history, and activity!`);
}

// Auto-run if executed directly
if (typeof require !== "undefined" && require.main === module) {
  seedDatabase();
}
